/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.misprogramas.views.panels;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Rodrigo
 */
public class pnlMoneda extends javax.swing.JPanel {

    /**
     * Creates new form pnlMoneda
     */
    public pnlMoneda() {
        initComponents();
    }

    public JButton getBtnConvToCordo() {
        return btnConvToCordo;
    }

    public JButton getBtnConvToDollar() {
        return btnConvToDollar;
    }

    public JButton getBtnNew() {
        return btnNew;
    }

    public JTextField getTxtCordoba() {
        return txtCordoba;
    }

    public JTextField getTxtDolar() {
        return txtDolar;
    }

    public void setBtnConvToCordo(JButton btnConvToCordo) {
        this.btnConvToCordo = btnConvToCordo;
    }

    public void setBtnConvToDollar(JButton btnConvToDollar) {
        this.btnConvToDollar = btnConvToDollar;
    }

    public void setBtnNew(JButton btnNew) {
        this.btnNew = btnNew;
    }

    public void setTxtCordoba(JTextField txtCordoba) {
        this.txtCordoba = txtCordoba;
    }

    public void setTxtDolar(JTextField txtDolar) {
        this.txtDolar = txtDolar;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCordoba = new javax.swing.JTextField();
        txtDolar = new javax.swing.JTextField();
        btnConvToDollar = new javax.swing.JButton();
        btnConvToCordo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnNew.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        btnNew.setText("Nuevo");
        jPanel1.add(btnNew);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Dubai Light", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Córdoba C$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Dubai Light", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Dólar U$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Conversion de moneda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel2.add(jLabel3, gridBagConstraints);

        txtCordoba.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCordobaKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 1, 2, 2);
        jPanel2.add(txtCordoba, gridBagConstraints);

        txtDolar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDolarKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 1, 2, 2);
        jPanel2.add(txtDolar, gridBagConstraints);

        btnConvToDollar.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        btnConvToDollar.setText("Convertir a U$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel2.add(btnConvToDollar, gridBagConstraints);

        btnConvToCordo.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        btnConvToCordo.setText("Convertir a C$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel2.add(btnConvToCordo, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Dubai Light", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("1$ = 35C$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        jPanel2.add(jLabel4, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCordobaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCordobaKeyTyped
        if (!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!= '.') {
            evt.consume();
        }
        if (evt.getKeyChar()=='.'&&txtCordoba.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCordobaKeyTyped

    private void txtDolarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDolarKeyTyped
        if (!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!= '.') {
            evt.consume();
        }
        if (evt.getKeyChar()=='.'&&txtDolar.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDolarKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvToCordo;
    private javax.swing.JButton btnConvToDollar;
    private javax.swing.JButton btnNew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCordoba;
    private javax.swing.JTextField txtDolar;
    // End of variables declaration//GEN-END:variables
}
