/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.misprogramas.views.panels;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Rodrigo
 */
public class pnlTemperatura extends javax.swing.JPanel {

    /**
     * Creates new form pnlTemperatura
     */
    public pnlTemperatura() {
        initComponents();
    }

    public JButton getBtnConvToC() {
        return btnConvToC;
    }

    public JButton getBtnConvToF() {
        return btnConvToF;
    }

    public JButton getBtnNew() {
        return btnNew;
    }

    public JTextField getTxtCelcious() {
        return txtCelcious;
    }

    public JTextField getTxtFahren() {
        return txtFahren;
    }

    public void setBtnConvToC(JButton btnConvToC) {
        this.btnConvToC = btnConvToC;
    }

    public void setBtnConvToF(JButton btnConvToF) {
        this.btnConvToF = btnConvToF;
    }

    public void setBtnNew(JButton btnNew) {
        this.btnNew = btnNew;
    }

    public void setTxtCelcious(JTextField txtCelcious) {
        this.txtCelcious = txtCelcious;
    }

    public void setTxtFahren(JTextField txtFahren) {
        this.txtFahren = txtFahren;
    }

    

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCelcious = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFahren = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnConvToF = new javax.swing.JButton();
        btnConvToC = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnNew.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        btnNew.setText("Nuevo");
        jPanel1.add(btnNew);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("C°");
        jLabel1.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel2.add(jLabel1, gridBagConstraints);

        txtCelcious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelciousActionPerformed(evt);
            }
        });
        txtCelcious.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelciousKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 7, 7, 7);
        jPanel2.add(txtCelcious, gridBagConstraints);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("F°");
        jLabel2.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        jPanel2.add(jLabel2, gridBagConstraints);

        txtFahren.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFahrenKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 7, 7, 7);
        jPanel2.add(txtFahren, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel2.add(jPanel3, gridBagConstraints);

        btnConvToF.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        btnConvToF.setText("Convertir a F°");
        btnConvToF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvToFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        jPanel2.add(btnConvToF, gridBagConstraints);

        btnConvToC.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        btnConvToC.setText("Convertir a C°");
        btnConvToC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvToCActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        jPanel2.add(btnConvToC, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Conversión de temperaturas");
        jPanel2.add(jLabel3, new java.awt.GridBagConstraints());

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvToFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvToFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConvToFActionPerformed

    private void txtCelciousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelciousActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelciousActionPerformed

    private void txtCelciousKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelciousKeyTyped
       if (!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!= '.') {
            evt.consume();
        }
        if (evt.getKeyChar()=='.'&&txtCelcious.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCelciousKeyTyped

    private void btnConvToCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvToCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConvToCActionPerformed

    private void txtFahrenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFahrenKeyTyped
        if (!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!= '.') {
            evt.consume();
        }
        if (evt.getKeyChar()=='.'&&txtFahren.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFahrenKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvToC;
    private javax.swing.JButton btnConvToF;
    private javax.swing.JButton btnNew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCelcious;
    private javax.swing.JTextField txtFahren;
    // End of variables declaration//GEN-END:variables
}
