/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.misprogramas.views.panels;


import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Rodrigo
 */
public class PnlViewVehicle extends javax.swing.JPanel {

    /**
     * Creates new form PnlViewVehicle
     */
    public PnlViewVehicle() {
        initComponents();
    }

   

    public JTable getTblViews() {
        return tblViews;
    }

    public JTextField getTxtBrowse() {
        return txtBrowse;
    }

    public JButton getBtnViewAll() {
        return btnViewAll;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        txtBrowse = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnViewAll = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViews = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(500, 550));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(309, 100));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        txtBrowse.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBrowseFocusLost(evt);
            }
        });
        txtBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrowseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(txtBrowse, gridBagConstraints);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Search:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabel1, gridBagConstraints);

        btnViewAll.setText("View All");
        btnViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 1;
        jPanel1.add(btnViewAll, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        tblViews.setBackground(new java.awt.Color(255, 255, 255));
        tblViews.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Stock", "Year", "Make", "Model", "Style", "VIN", "Esterior Color", "Interior Color", "Miles", "Price", "Transmission", "Engine", "Image", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblViews.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblViews.setName(""); // NOI18N

        tblViews.setRowHeight(30);
        jScrollPane1.setViewportView(tblViews);
        if (tblViews.getColumnModel().getColumnCount() > 0) {
            tblViews.getColumnModel().getColumn(0).setHeaderValue("Stock");
            tblViews.getColumnModel().getColumn(1).setHeaderValue("Year");
            tblViews.getColumnModel().getColumn(2).setHeaderValue("Make");
            tblViews.getColumnModel().getColumn(3).setHeaderValue("Model");
            tblViews.getColumnModel().getColumn(4).setHeaderValue("Style");
            tblViews.getColumnModel().getColumn(5).setHeaderValue("VIN");
            tblViews.getColumnModel().getColumn(6).setHeaderValue("Esterior Color");
            tblViews.getColumnModel().getColumn(7).setHeaderValue("Interior Color");
            tblViews.getColumnModel().getColumn(8).setHeaderValue("Miles");
            tblViews.getColumnModel().getColumn(9).setHeaderValue("Price");
            tblViews.getColumnModel().getColumn(10).setHeaderValue("Transmission");
            tblViews.getColumnModel().getColumn(11).setHeaderValue("Engine");
            tblViews.getColumnModel().getColumn(12).setHeaderValue("Image");
            tblViews.getColumnModel().getColumn(13).setHeaderValue("Status");
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel2.add(jScrollPane1, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrowseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrowseActionPerformed

    private void txtBrowseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBrowseFocusLost
        //if (txtBrowse.getText().isEmpty()) {
        //    txtBrowse.requestFocus();
        //    txtBrowse.setBorder(new LineBorder(Color.RED, 2));
        //    return;
        //}
        //txtBrowse.setBorder(null);
    }//GEN-LAST:event_txtBrowseFocusLost

    private void btnViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewAllActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblViews;
    private javax.swing.JTextField txtBrowse;
    // End of variables declaration//GEN-END:variables
}
