/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.misprogramas.views;

import java.awt.BorderLayout;
import ni.edu.uni.misprogramas.controllers.pnlCalculadoraController;
import ni.edu.uni.misprogramas.controllers.pnlMonedaController;
import ni.edu.uni.misprogramas.controllers.pnlTemperaturaController;
import ni.edu.uni.misprogramas.views.panels.pnlCalculadora;
import ni.edu.uni.misprogramas.views.panels.pnlMoneda;
import ni.edu.uni.misprogramas.views.panels.pnlTemperatura;


/**
 *
 * @author Rodrigo
 */
public class StartFrame extends javax.swing.JFrame {
    private pnlCalculadora pnlCalc;
    private pnlTemperatura pnlTemp;
    private pnlMoneda pnlMone;
    private pnlCalculadoraController pnlCalcController;
    private pnlTemperaturaController pnlTempController;
    private pnlMonedaController pnlMoneController;
    /**
     * Creates new form StartFrame
     */
    public StartFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLeftButtons = new javax.swing.JPanel();
        btnCalc = new javax.swing.JButton();
        btnTemp = new javax.swing.JButton();
        btnMoney = new javax.swing.JButton();
        pnlContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My app");
        setName("frame1"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 500));

        pnlLeftButtons.setBackground(new java.awt.Color(153, 153, 153));
        pnlLeftButtons.setPreferredSize(new java.awt.Dimension(120, 100));
        pnlLeftButtons.setLayout(new java.awt.GridLayout(3, 1, 2, 2));

        btnCalc.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        btnCalc.setForeground(new java.awt.Color(0, 0, 0));
        btnCalc.setText("Calculadora");
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });
        pnlLeftButtons.add(btnCalc);

        btnTemp.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        btnTemp.setForeground(new java.awt.Color(0, 0, 0));
        btnTemp.setText("Temperatura");
        btnTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTempActionPerformed(evt);
            }
        });
        pnlLeftButtons.add(btnTemp);

        btnMoney.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        btnMoney.setForeground(new java.awt.Color(0, 0, 0));
        btnMoney.setText("Moneda");
        btnMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoneyActionPerformed(evt);
            }
        });
        pnlLeftButtons.add(btnMoney);

        getContentPane().add(pnlLeftButtons, java.awt.BorderLayout.LINE_START);

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlContent.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        if(pnlCalc == null){
            pnlCalc = new pnlCalculadora();
            pnlCalcController = new pnlCalculadoraController(pnlCalc);
        }
        if(pnlContent.getComponentCount() > 0){
            pnlContent.remove(0);
        }
        pnlContent.add(pnlCalc, BorderLayout.CENTER);
        this.validate();
    }//GEN-LAST:event_btnCalcActionPerformed

    private void btnTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTempActionPerformed
        if(pnlTemp == null){
            pnlTemp = new pnlTemperatura();
            pnlTempController = new pnlTemperaturaController(pnlTemp);
        }
        if(pnlContent.getComponentCount() > 0){
            pnlContent.remove(0);
        }
        pnlContent.add(pnlTemp, BorderLayout.CENTER);
        this.validate();
    }//GEN-LAST:event_btnTempActionPerformed

    private void btnMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoneyActionPerformed
        if(pnlMone == null){
            pnlMone = new pnlMoneda();
            pnlMoneController = new pnlMonedaController(pnlMone);
        }
        if(pnlContent.getComponentCount() > 0){
            pnlContent.remove(0);
        }
        pnlContent.add(pnlMone, BorderLayout.CENTER);
        this.validate();
    }//GEN-LAST:event_btnMoneyActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc;
    private javax.swing.JButton btnMoney;
    private javax.swing.JButton btnTemp;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlLeftButtons;
    // End of variables declaration//GEN-END:variables
}
